import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layouts/Header";
import NavigationBar from "./components/layouts/NavigationBar";
import Footer from "./components/layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased`}>
        <Header />
        <div className="mx-auto max-w-screen-xl border-x border-black text-black">
          <NavigationBar />
          <div className="px-7">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
